feat: 95351 - [Telemetry] Add debug log
plentymarkets/mc-telemetry-driver pull request #1
Opened 2024-02-21 10:42 UTC by dvatan-plenty

feat: AB#95351: [Telemetry] Add debug log

2024-02-21 12:48 UTC, pduca-plenty approved these changes, later dismissed

2024-02-22 13:44 UTC, mbrueschke requested changes

2024-02-22 13:44 UTC, mbrueschke commented on pkg/teldrvr/newrelicAPM.go
> +	segmentsStartWasLogged map[string]struct{}
why was this added?

2024-02-22 13:44 UTC, mbrueschke commented on pkg/teldrvr/newrelicAPM.go
> +	// TODO - Will be implemented as in Error()
why will this be implemented as in Error()?

Have you taken a look into t.transaction.RecordLog() for logging

2024-02-22 13:44 UTC, mbrueschke commented on pkg/teldrvr/newrelicAPM.go
> +	// TODO - Will be implemented as in Error()
if possible we might want to be able to log debug and info with the record log

2024-02-26 12:31 UTC, mbrueschke commented on pkg/teldrvr/newrelicAPM.go
> +	recordLog.Severity = "Debug"
info

2024-02-27 07:47 UTC, mbrueschke commented on pkg/teldrvr/newrelicAPM.go
> +// Debug [NOT IMPLEMENTED]
comment says that this function is not implemented ^^

2024-02-27 07:47 UTC, mbrueschke approved these changes, later dismissed

2024-02-27 08:00 UTC, mbrueschke approved these changes

2024-02-27 08:02 UTC, merged