feat: AB#95352 - Add log level
plentymarkets/mc-telemetry-driver pull request #23
Opened 2024-02-12 07:30 UTC by dvatan-plenty

feat: AB#95352 - Add log level

2024-02-12 10:32 UTC, mbrueschke requested changes

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/config.go
> +	viper.BindEnv("telemetry.debug", "TELEMETRY_DEBUG")
a better name would be `viper.BindEnv("telemetry.logLevel", "TELEMETRY_LOGLEVEL")`

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/config.go
> +	viper.SetDefault("telemetry.debug", "all")
The default should be error

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	"all":   0, // Default value
we should not be in the need of all, since that should be covered by the debug log level

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +var debugOptions = map[string]int{
why do we need the map and not use the string values instead?

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +var debug int
this should be called something like `activeLogLevel`

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	segmentIDs map[string]struct{}
Dont we already got the segmentIDs as key in the segments map?

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +type SegmentIDs struct {
the whole struct + its method are not safe for concurrent use. We can not assume that the order of started segments and segment ends are done in a specific one. It might be that segment a is started and shortly after segment b is ended. With this implementation we would have a race since peek and pop are not related to the segmentIds

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	segmentIDs       *SegmentIDs
Why do we have segmentIDs two times? One time here and a second time in the container?

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	t.segmentIDs = &SegmentIDs{[]string{}}
make use of a new function instead of initializing a struct like that

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +func (segmentIDs *SegmentIDs) Push(segmentID string) {
not save for concurrent use

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> -	log.Printf("Segment start[%s]: %s \n", segmentID, name)
the start will now not be written anymore if the segment was started, even on debug level

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if debug > DebugLevel {
We will never write the segment start unless we have the level 1 here. But that is not right. If we would have an error or info and the level is set accoringly we should write a segment start and a segment end

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +		// TODO - Implement Case when somebody forgot to close a segment
todo, but this is also not working, so that will need to be refactored completely anyway

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if debug > DebugLevel {
same as segmentWriteStart

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	// TODO - retrieve the last element of the array.
TODO, and also not right. We do not want to get the last entry, we want to get the right entry

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +func (t *LocalTransaction) LogError(readCloser io.ReadCloser) error {
unused function

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if debug > ErrorLevel {
We always want to log errors, so we do not need the if

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	currentSegmentID := t.segmentIDs.Peek()
not right, since we want to have the right segment not the last one.

2024-02-12 10:32 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +func (t *LocalTransaction) LogInfo(readCloser io.ReadCloser) error {
unused function

2024-02-12 11:10 UTC, dvatan-plenty commented on pkg/teldrvr/config.go
> +	viper.BindEnv("telemetry.debug", "TELEMETRY_DEBUG")
Changed. Thank you.

2024-02-12 13:04 UTC, dvatan-plenty commented on pkg/teldrvr/local.go
> +var debugOptions = map[string]int{
Removed this implementation

2024-02-13 12:15 UTC, mbrueschke requested changes

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> -	log.Printf("Segment start[%s]: %s \n", segmentID, name)
the segment start should only be written on call if the log level is error. Otherwise it should be written on events like info or, later on, debug

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	var err error
why adding err here?

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if err != nil {
err will be nil everytime, so no need to check here

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	ok := false
`var ok bool` instead

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if activeLogLevel == ErrorLevel || activeLogLevel == InfoLevel {
so we do not write the segment end if the log level is error or info? 

Then when do we write the end at all?

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	t.segmentWriteEnd(segmentID)
error not handled

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	t.segmentWriteStart(segmentID)
what happens if multiple errors are thrown in the same segment? We would write it multiple times

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if activeLogLevel == ErrorLevel || activeLogLevel == InfoLevel {
so we do not write the info if the log level is error or info?

Then when do we write the info at all?

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	t.segmentWriteStart(segmentID)
what happens if multiple infos are thrown in the same segment? We would write it multiple times?

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	if activeLogLevel == ErrorLevel || activeLogLevel == InfoLevel {
there is no check if the write log was already written for the segment

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
> +	t.segmentWriteEnd(segmentID)
should only be written if the segment start was written

2024-02-13 12:15 UTC, mbrueschke commented on pkg/teldrvr/local.go
>  	delete(t.segmentContainer.segments, segmentID)
the container fields need to be cleared in SegmentEnd func

2024-02-14 06:54 UTC, closed without merging